name: build the LVK virtualenv

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      -
        uses: actions/checkout@v1
      -
        env:
          OSG_ACCESS: "${{secrets.OSG_ACCESS}}"
        name: "Preparing ssh stuff"
        run: "bash -e tools/docker_build_prepssh.sh"
      -
        env:
          DOCKER_IMG: igwn/base:el8
          PYCBC_CONTAINER: pycbc_rhel_virtualenv
          DOCKER_SECURE_ENV_VARS: true
        name: "Creating the virtual environment"
        run: "pytest examples/workflow/data_checker/daily_test.py pycbc/workflow/configparser_test.py test/test_array.py test/test_array_lal.py test/test_autochisq.py test/test_bhspec.py test/test_calibration.py test/test_chisq.py test/test_coinc_stat.py test/test_constants.py test/test_conversions.py test/test_coordinates_space.py test/test_correlate.py test/test_cuts.py test/test_detector.py test/test_distributions.py test/test_dq.py test/test_fft_mkl_threaded.py test/test_fft_unthreaded.py test/test_fftw_openmp.py test/test_fftw_pthreads.py test/test_frame.py test/test_frequencyseries.py test/test_infmodel.py test/test_injection.py test/test_io_gracedb.py test/test_io_hdf.py test/test_io_hgroup.py test/test_live_coinc_compare.py test/test_matchedfilter.py test/test_noise.py test/test_pnutils.py test/test_psd.py test/test_resample.py test/test_results_dq.py test/test_schemes.py test/test_significance_module.py test/test_skymax.py test/test_spatmplt.py test/test_strain.py test/test_threshold.py test/test_time.py test/test_timeseries.py test/test_tmpltbank.py test/test_transforms.py test/test_waveform.py test/test_waveform_utils.py"
